
SEGMENTS = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

rule all:
    input:
        auspice_tree = expand("auspice/btv_segment{segment}_tree.json", segment=segments)
        auspice_meta = expand("auspice/btv_segment{segment}_meta.json", segment=segments)
